create table if not exists public.wishlist_price_history (
  id bigint generated by default as identity primary key,
  wishlist_item_id bigint not null references public.wishlist_items(id) on delete cascade,
  price numeric not null,
  created_at timestamptz not null default now()
);

create index if not exists wishlist_price_history_item_id_idx on public.wishlist_price_history(wishlist_item_id);
