name: Nightly Backup

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v4
      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client
      - name: Dump schema
        run: pg_dump --schema-only "$DATABASE_URL" > schema.sql
      - name: Dump data
        run: pg_dump --data-only --inserts "$DATABASE_URL" > seed.sql
      - uses: actions/upload-artifact@v4
        with:
          name: supabase-backup
          path: |
            schema.sql
            seed.sql
